Enum customer_role_enum {
  owner
  admin
}

Table customer {
  id uuid [pk, increment]
  first_name varchar
  last_name varchar
  email varchar [unique]
  encrypted_password varchar
  password_salt varchar
  app_id uuid [ref: > app.id]
  role customer_role_enum
}