Table member {
  id int [pk, increment]
  app_id int [ref: > app.id]
  first_name varchar
  last_name varchar
}

Table member_file {
  id int
  member_id int [ref: > member.id]
  file_id int [ref: > file.id]
  Note: 'Member uploadings'
}

Enum member_role_enum {
  moderator
}

Table member_role {
  id int
  member_id int [ref: > member.id]
  role member_role_enum
}
