version: '3.7'
services:
  postgres:
    container_name: chat-app-postgres-1
    image: mdillon/postgis
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: chat
    volumes:
      - postgres:/var/lib/postgresql/data
  graphql-engine:
    container_name: chat-app-graphql-engine
    image: hasura/graphql-engine:v2.15.2
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://chatuser:chatpass@postgres:5432/chat
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_ADMIN_SECRET: chat
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256", "key":"-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyyCeIzIABTM1tuO8WNRk\nY9Zl32CYnueiu4JQlGnKTl1WSKnUwN1yixAlObuCpKLFXPeiKPs0Gkf6aCUNmkfN\n1OGuWkksQLRaZ8Kzu4Lp7H0jioivSot3unvpTERRlHAiBQWmpP9N/tcWkuB6JII5\nkZLiDFFi5E7/wajHey4y7Jjx5EDcle8qEjDUwkamOgB5KI52hyllJYvpHWL3riC7\n/DLT4EVcT+PqlwdNckCKf9rF0y1fE1Pg93LlWvZQwKVXpbfyqZ+3ITw4D8iag04c\nn//wdorFO5b3wnzIglplwzTmCRZJ7jmbBAc8swuPIgjSo/1hJjZZzEtoVICcjFQF\nnwIDAQAB\n-----END PUBLIC KEY-----\n"}'
      HASURA_GRAPHQL_ACCESS_KEY: 'chat'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'public'
      HASURA_GRAPHQL_MIGRATIONS_DIR: '/hasura/migrations'
      HASURA_GRAPHQL_METADATA_DIR: '/hasura/metadata'
      MANAGER_EVENT_WEBHOOK_ENDPOINT: http://host.docker.internal:4203/api/hasura/events
      MANAGER_GRAPHQL_URL: http://host.docker.internal:4203/graphql
      HASURA_MANAGER_WEBHOOK_SECRET_HEADER_VALUE: secret1
      HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: true
    volumes:
      - ./hasura:/hasura/
volumes:
  postgres:
