name: Deploy dbdocs

on:
  push:
    branches: [master]
    paths:
      - 'apps/dbdocs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.17.0
      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm nx build dbdocs --prod

      - name: Deploy
        run: node dist/apps/dbdocs/main.js
