name: Deploy dbdocs to cloud

on:
  push:
    branches: [master]

jobs:
  Build_Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn nx build dbdocs --prod

      - name: Deploy
        run: node dist/apps/dbdocs/main.js
