name: Deploy manager prod

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.17.0
      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: |
          pnpm nx build manager --prod
          cp pnpm-lock.yaml dist/apps/manager
          cd dist/apps/manager
          pnpm install
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: manager-railway-prod
          FOLDER: dist/apps/manager
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: 'Build: ({sha}) {msg}'
